import res_partner
import carte
import sold_transfert
import product
import chargeur
import sous_chargeur
import historique
import historique_dispatch
import benificiaire,beneficire,customer
import api
import historique_ben
import statistique
import statistique_client
import product_report
import point_vente
import versement
import achats_order
import ticket_valeur,tv_impression,tv_print,tv_print_hestory,tv_type
import tv_facute_numbers
import commercial
import releve_compte
import releve_caissier_tresorier
import demande_credit
import carte_pre_imprime
import releve_tv_client
import historiqueKkiapay
import recharge_par_carte
# import multi_company
import excel
import kilometrage
import rapport_kilometrage