{
    'name': 'benin_petro_tv',
    'version': '1.0',
    'summary': 'Groupe BENIN PETRO',
    'description': '',
    'category': 'Groupe BENIN PETRO',
    'author': 'SOFT-SOLUTION',
    'website': '',
    'license': '',
    'depends': ['base','report','product','web_eradicate_duplicate','purchase','report_xlsx'],
    'data': [
        'security/res_groups.xml',
        'security/ir_rule.xml',
        'security/ir.model.access.csv',
        
        'wizard/recharge_wizard.xml',
        'wizard/sous_recharge_wizard.xml',
        'wizard/recharger_compte_wizard.xml',
        'wizard/tv_impression_wizard.xml',
        'wizard/tv_impression_remise_wizard.xml',
        'wizard/sous_recharge_wizard_tv.xml',        
        'wizard/recharge_wizard_tv.xml',
        'wizard/confirm_versement_wizard.xml',
        'wizard/point_vente_payment_wizard_view.xml',
        'wizard/retour_bon_consommation_wizard.xml',
        'wizard/chiffre_affaire_par_client_wizard.xml',

         'views/res_partner_view.xml',
         'views/carte_view.xml',
         'views/product_views.xml',
         'views/point_vente_view.xml',
         'views/agent_point_vente_view.xml',
         'views/type_carte_view.xml',
         'views/transaction_view.xml',
        'views/statistiques_view.xml',
        'views/statistiques_client_view.xml',
        #'views/stock_picking_view.xml',
        #'views/transport_view.xml',
        #'views/location_view.xml',
        'views/sold_transfert_view.xml',
         'views/customer_view.xml',
        # 'views/vehicle_translate.xml',
        # 'views/chauffeur_translate.xml',
        #'views/transport_cache.xml',
        # 'views/article_view.xml',
	    # 'views/article_view2.xml',
         'views/versement_view.xml',
        # 'views/bon_de_commande_view.xml',
         'views/historique_view.xml',
        # 'views/facture_view.xml',
         'views/tv_type_view.xml',
         'views/ticket_valeur_view.xml',
         'views/tv_print_view.xml',
        # #'views/transfer_view.xml',
         'views/sous_chargeur_view.xml',
         'views/chargeur_view.xml',
         'views/commercial_view.xml',
         'views/menu/menu_client_view.xml',
         'views/menu/menu_promoteur_view.xml',

         'data/report_paperformat_data.xml',

         'reports/carte_repport.xml',
         'reports/facture_recharge_easy.xml',
         'reports/facture_de_ticket.xml',
         'reports/tv_repport.xml',
         'reports/tv_repport2.xml',
         'reports/bl_tv.xml',
         'reports/facture_promoteur.xml',
         'reports/point_jour_report.xml',
         'reports/vente_tv_par_jour_report.xml',
         'reports/vente_easy_par_jour_report.xml',
         'reports/achat_tv_par_jour_report.xml',
         'reports/achat_easy_par_jour_report.xml',
         'reports/facture_paiment_acredit.xml',
         'reports/bon_commande_monnaie.xml',
         'reports/etat_tv_report.xml',
         'reports/etat_tv_code_report.xml',
         'reports/detail_tv_xlsx_report.xml',
         'reports/report_recharge_par_carte.xml',
         'reports/etat_releve_compte_client.xml',
         'reports/etat_releve_caissier_tresorier.xml',
         'reports/report_excel/retour_bon_consommation_xlsx_report.xml',
         'reports/report_excel/suivie_compte_client_xlsx_report.xml',
         'reports/report_excel/suivie_compte_carte_xlsx_report.xml',
         'reports/report_excel/releve_tresorier_xlsx_report.xml',
         'reports/report_excel/releve_caissier_xlsx_report.xml',
         'reports/report_excel/releve_kilometrage_xlsx_report.xml',
         'reports/report_excel/detail_retour_tv_xlsx_report.xml',
         'reports/kilometrage_report.xml',
         'static/xml/data.xml',
        #  'views/top_menu.xml',
         'views/menu_view.xml',
    ],
    'qweb': [
        'data/base.xml',
        'static/xml/widget_statistiques.xml',
    ],
    'css': ['static/css/style.css'],
    'js': ['static/js/qrcode.js'],
    'installable': True,
    'auto_install': False,
}
