import recharge_compte
import recharge
import tv_impression
import tv_impression_remise
import rechargetv
import versement_wizard
import point_vente_payment_wizard
import retour_bon_consommation
import chiffre_affaire_wizard
import detail_consommation_par_carte
import point_jour
import etat_gouverneur_tresorier_wizard
import etat_gouverneur_agent_wizard
import vente_tv_par_jour
import vente_easy_par_jour
import achat_easy_par_jour
import achat_tv_par_jour
import add_paiment_credit
import bon_commande_monaie
import etat_tv
import recharge_gerant
import detail_retour_tv
import chiffre_affaire_par_client