# coding: utf-8

"""
    API iSendPro

    [1] Liste des fonctionnalités : - envoi de SMS à un ou plusieurs destinataires, - lookup HLR, - récupération des récapitulatifs de campagne, - gestion des répertoires, - ajout en liste noire. - comptage du nombre de caractères des SMS  [2] Pour utiliser cette API vous devez: - Créer un compte iSendPro sur https://isendpro.com/ - Créditer votre compte      - Remarque: obtention d'un crédit de test possible sous conditions - Noter votre clé de compte (keyid)   - Elle vous sera indispensable à l'utilisation de l'API   - Vous pouvez la trouver dans le rubrique mon \"compte\", sous-rubrique \"mon API\" - Configurer le contrôle IP   - Le contrôle IP est configurable dans le rubrique mon \"compte\", sous-rubrique \"mon API\"   - Il s'agit d'un système de liste blanche, vous devez entrer les IP utilisées pour appeler l'API   - Vous pouvez également désactiver totalement le contrôle IP   # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: support@isendpro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class REPERTOIREcreatereponseEtatEtat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'repertoire_id': 'str',
        'message': 'str'
    }

    attribute_map = {
        'code': 'code',
        'repertoire_id': 'repertoireId',
        'message': 'message'
    }

    def __init__(self, code=None, repertoire_id=None, message=None):  # noqa: E501
        """REPERTOIREcreatereponseEtatEtat - a model defined in Swagger"""  # noqa: E501

        self._code = None
        self._repertoire_id = None
        self._message = None
        self.discriminator = None

        self.code = code
        if repertoire_id is not None:
            self.repertoire_id = repertoire_id
        if message is not None:
            self.message = message

    @property
    def code(self):
        """Gets the code of this REPERTOIREcreatereponseEtatEtat.  # noqa: E501

        Code retour. Voir \"tableau des code retour\" dans l'annexe de la documentation  # noqa: E501

        :return: The code of this REPERTOIREcreatereponseEtatEtat.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this REPERTOIREcreatereponseEtatEtat.

        Code retour. Voir \"tableau des code retour\" dans l'annexe de la documentation  # noqa: E501

        :param code: The code of this REPERTOIREcreatereponseEtatEtat.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def repertoire_id(self):
        """Gets the repertoire_id of this REPERTOIREcreatereponseEtatEtat.  # noqa: E501

        repertoireId du repertoire crée.  # noqa: E501

        :return: The repertoire_id of this REPERTOIREcreatereponseEtatEtat.  # noqa: E501
        :rtype: str
        """
        return self._repertoire_id

    @repertoire_id.setter
    def repertoire_id(self, repertoire_id):
        """Sets the repertoire_id of this REPERTOIREcreatereponseEtatEtat.

        repertoireId du repertoire crée.  # noqa: E501

        :param repertoire_id: The repertoire_id of this REPERTOIREcreatereponseEtatEtat.  # noqa: E501
        :type: str
        """

        self._repertoire_id = repertoire_id

    @property
    def message(self):
        """Gets the message of this REPERTOIREcreatereponseEtatEtat.  # noqa: E501

        Libellé associé au code retour.  # noqa: E501

        :return: The message of this REPERTOIREcreatereponseEtatEtat.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this REPERTOIREcreatereponseEtatEtat.

        Libellé associé au code retour.  # noqa: E501

        :param message: The message of this REPERTOIREcreatereponseEtatEtat.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, REPERTOIREcreatereponseEtatEtat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
