# coding: utf-8

"""
    API iSendPro

    [1] Liste des fonctionnalités : - envoi de SMS à un ou plusieurs destinataires, - lookup HLR, - récupération des récapitulatifs de campagne, - gestion des répertoires, - ajout en liste noire. - comptage du nombre de caractères des SMS  [2] Pour utiliser cette API vous devez: - Créer un compte iSendPro sur https://isendpro.com/ - Créditer votre compte      - Remarque: obtention d'un crédit de test possible sous conditions - Noter votre clé de compte (keyid)   - Elle vous sera indispensable à l'utilisation de l'API   - Vous pouvez la trouver dans le rubrique mon \"compte\", sous-rubrique \"mon API\" - Configurer le contrôle IP   - Le contrôle IP est configurable dans le rubrique mon \"compte\", sous-rubrique \"mon API\"   - Il s'agit d'un système de liste blanche, vous devez entrer les IP utilisées pour appeler l'API   - Vous pouvez également désactiver totalement le contrôle IP   # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: support@isendpro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SubaccountAddRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'keyid': 'str',
        'sub_account_edit': 'str',
        'sub_account_login': 'str',
        'sub_account_password': 'str'
    }

    attribute_map = {
        'keyid': 'keyid',
        'sub_account_edit': 'subAccountEdit',
        'sub_account_login': 'subAccountLogin',
        'sub_account_password': 'subAccountPassword'
    }

    def __init__(self, keyid=None, sub_account_edit=None, sub_account_login=None, sub_account_password=None):  # noqa: E501
        """SubaccountAddRequest - a model defined in Swagger"""  # noqa: E501

        self._keyid = None
        self._sub_account_edit = None
        self._sub_account_login = None
        self._sub_account_password = None
        self.discriminator = None

        self.keyid = keyid
        self.sub_account_edit = sub_account_edit
        self.sub_account_login = sub_account_login
        self.sub_account_password = sub_account_password

    @property
    def keyid(self):
        """Gets the keyid of this SubaccountAddRequest.  # noqa: E501


        :return: The keyid of this SubaccountAddRequest.  # noqa: E501
        :rtype: str
        """
        return self._keyid

    @keyid.setter
    def keyid(self, keyid):
        """Sets the keyid of this SubaccountAddRequest.


        :param keyid: The keyid of this SubaccountAddRequest.  # noqa: E501
        :type: str
        """
        if keyid is None:
            raise ValueError("Invalid value for `keyid`, must not be `None`")  # noqa: E501

        self._keyid = keyid

    @property
    def sub_account_edit(self):
        """Gets the sub_account_edit of this SubaccountAddRequest.  # noqa: E501


        :return: The sub_account_edit of this SubaccountAddRequest.  # noqa: E501
        :rtype: str
        """
        return self._sub_account_edit

    @sub_account_edit.setter
    def sub_account_edit(self, sub_account_edit):
        """Sets the sub_account_edit of this SubaccountAddRequest.


        :param sub_account_edit: The sub_account_edit of this SubaccountAddRequest.  # noqa: E501
        :type: str
        """
        if sub_account_edit is None:
            raise ValueError("Invalid value for `sub_account_edit`, must not be `None`")  # noqa: E501
        allowed_values = ["addAccount"]  # noqa: E501
        if sub_account_edit not in allowed_values:
            raise ValueError(
                "Invalid value for `sub_account_edit` ({0}), must be one of {1}"  # noqa: E501
                .format(sub_account_edit, allowed_values)
            )

        self._sub_account_edit = sub_account_edit

    @property
    def sub_account_login(self):
        """Gets the sub_account_login of this SubaccountAddRequest.  # noqa: E501


        :return: The sub_account_login of this SubaccountAddRequest.  # noqa: E501
        :rtype: str
        """
        return self._sub_account_login

    @sub_account_login.setter
    def sub_account_login(self, sub_account_login):
        """Sets the sub_account_login of this SubaccountAddRequest.


        :param sub_account_login: The sub_account_login of this SubaccountAddRequest.  # noqa: E501
        :type: str
        """
        if sub_account_login is None:
            raise ValueError("Invalid value for `sub_account_login`, must not be `None`")  # noqa: E501

        self._sub_account_login = sub_account_login

    @property
    def sub_account_password(self):
        """Gets the sub_account_password of this SubaccountAddRequest.  # noqa: E501


        :return: The sub_account_password of this SubaccountAddRequest.  # noqa: E501
        :rtype: str
        """
        return self._sub_account_password

    @sub_account_password.setter
    def sub_account_password(self, sub_account_password):
        """Sets the sub_account_password of this SubaccountAddRequest.


        :param sub_account_password: The sub_account_password of this SubaccountAddRequest.  # noqa: E501
        :type: str
        """
        if sub_account_password is None:
            raise ValueError("Invalid value for `sub_account_password`, must not be `None`")  # noqa: E501

        self._sub_account_password = sub_account_password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubaccountAddRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
