# coding: utf-8

"""
    API iSendPro

    [1] Liste des fonctionnalités : - envoi de SMS à un ou plusieurs destinataires, - lookup HLR, - récupération des récapitulatifs de campagne, - gestion des répertoires, - ajout en liste noire. - comptage du nombre de caractères des SMS  [2] Pour utiliser cette API vous devez: - Créer un compte iSendPro sur https://isendpro.com/ - Créditer votre compte      - Remarque: obtention d'un crédit de test possible sous conditions - Noter votre clé de compte (keyid)   - Elle vous sera indispensable à l'utilisation de l'API   - Vous pouvez la trouver dans le rubrique mon \"compte\", sous-rubrique \"mon API\" - Configurer le contrôle IP   - Le contrôle IP est configurable dans le rubrique mon \"compte\", sous-rubrique \"mon API\"   - Il s'agit d'un système de liste blanche, vous devez entrer les IP utilisées pour appeler l'API   - Vous pouvez également désactiver totalement le contrôle IP   # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: support@isendpro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SubaccountResponseEtatEtat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'message': 'str',
        'sub_account_id': 'str',
        'sub_account_keyid': 'str'
    }

    attribute_map = {
        'code': 'code',
        'message': 'message',
        'sub_account_id': 'subAccountId',
        'sub_account_keyid': 'subAccountKeyid'
    }

    def __init__(self, code=None, message=None, sub_account_id=None, sub_account_keyid=None):  # noqa: E501
        """SubaccountResponseEtatEtat - a model defined in Swagger"""  # noqa: E501

        self._code = None
        self._message = None
        self._sub_account_id = None
        self._sub_account_keyid = None
        self.discriminator = None

        if code is not None:
            self.code = code
        if message is not None:
            self.message = message
        if sub_account_id is not None:
            self.sub_account_id = sub_account_id
        if sub_account_keyid is not None:
            self.sub_account_keyid = sub_account_keyid

    @property
    def code(self):
        """Gets the code of this SubaccountResponseEtatEtat.  # noqa: E501


        :return: The code of this SubaccountResponseEtatEtat.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this SubaccountResponseEtatEtat.


        :param code: The code of this SubaccountResponseEtatEtat.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def message(self):
        """Gets the message of this SubaccountResponseEtatEtat.  # noqa: E501


        :return: The message of this SubaccountResponseEtatEtat.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this SubaccountResponseEtatEtat.


        :param message: The message of this SubaccountResponseEtatEtat.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def sub_account_id(self):
        """Gets the sub_account_id of this SubaccountResponseEtatEtat.  # noqa: E501


        :return: The sub_account_id of this SubaccountResponseEtatEtat.  # noqa: E501
        :rtype: str
        """
        return self._sub_account_id

    @sub_account_id.setter
    def sub_account_id(self, sub_account_id):
        """Sets the sub_account_id of this SubaccountResponseEtatEtat.


        :param sub_account_id: The sub_account_id of this SubaccountResponseEtatEtat.  # noqa: E501
        :type: str
        """

        self._sub_account_id = sub_account_id

    @property
    def sub_account_keyid(self):
        """Gets the sub_account_keyid of this SubaccountResponseEtatEtat.  # noqa: E501


        :return: The sub_account_keyid of this SubaccountResponseEtatEtat.  # noqa: E501
        :rtype: str
        """
        return self._sub_account_keyid

    @sub_account_keyid.setter
    def sub_account_keyid(self, sub_account_keyid):
        """Sets the sub_account_keyid of this SubaccountResponseEtatEtat.


        :param sub_account_keyid: The sub_account_keyid of this SubaccountResponseEtatEtat.  # noqa: E501
        :type: str
        """

        self._sub_account_keyid = sub_account_keyid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubaccountResponseEtatEtat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
