# coding: utf-8

# flake8: noqa

"""
    API iSendPro

    [1] Liste des fonctionnalités : - envoi de SMS à un ou plusieurs destinataires, - lookup HLR, - récupération des récapitulatifs de campagne, - gestion des répertoires, - ajout en liste noire. - comptage du nombre de caractères des SMS  [2] Pour utiliser cette API vous devez: - Créer un compte iSendPro sur https://isendpro.com/ - Créditer votre compte      - Remarque: obtention d'un crédit de test possible sous conditions - Noter votre clé de compte (keyid)   - Elle vous sera indispensable à l'utilisation de l'API   - Vous pouvez la trouver dans le rubrique mon \"compte\", sous-rubrique \"mon API\" - Configurer le contrôle IP   - Le contrôle IP est configurable dans le rubrique mon \"compte\", sous-rubrique \"mon API\"   - Il s'agit d'un système de liste blanche, vous devez entrer les IP utilisées pour appeler l'API   - Vous pouvez également désactiver totalement le contrôle IP   # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: support@isendpro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.add_shortlink_api import AddShortlinkApi
from swagger_client.api.add_subaccount_api import AddSubaccountApi
from swagger_client.api.campagne_api import CampagneApi
from swagger_client.api.comptage_api import ComptageApi
from swagger_client.api.credit_api import CreditApi
from swagger_client.api.del_liste_noire_api import DelListeNoireApi
from swagger_client.api.edit_subaccount_api import EditSubaccountApi
from swagger_client.api.get_liste_noire_api import GetListeNoireApi
from swagger_client.api.hlr_api import HlrApi
from swagger_client.api.repertoire_api import RepertoireApi
from swagger_client.api.set_liste_noire_api import SetListeNoireApi
from swagger_client.api.sms_api import SmsApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.comptage_reponse import ComptageReponse
from swagger_client.models.comptage_reponse_etat import ComptageReponseEtat
from swagger_client.models.comptage_reponse_etat_etat import ComptageReponseEtatEtat
from swagger_client.models.comptage_request import ComptageRequest
from swagger_client.models.credit_response import CreditResponse
from swagger_client.models.credit_response_etat import CreditResponseEtat
from swagger_client.models.erreur import Erreur
from swagger_client.models.erreur_etat import ErreurEtat
from swagger_client.models.erreur_etat_etat import ErreurEtatEtat
from swagger_client.models.hlr_reponse import HLRReponse
from swagger_client.models.hlr_reponse_etat import HLRReponseEtat
from swagger_client.models.hlr_reponse_etat_etat import HLRReponseEtatEtat
from swagger_client.models.hl_rrequest import HLRrequest
from swagger_client.models.listenoire_reponse import LISTENOIREReponse
from swagger_client.models.listenoire_reponse_etat import LISTENOIREReponseEtat
from swagger_client.models.listenoire_reponse_etat_etat import LISTENOIREReponseEtatEtat
from swagger_client.models.repertoir_ecreatereponse import REPERTOIREcreatereponse
from swagger_client.models.repertoir_ecreatereponse_etat import REPERTOIREcreatereponseEtat
from swagger_client.models.repertoir_ecreatereponse_etat_etat import REPERTOIREcreatereponseEtatEtat
from swagger_client.models.repertoir_ecreaterequest import REPERTOIREcreaterequest
from swagger_client.models.repertoir_emodifreponse import REPERTOIREmodifreponse
from swagger_client.models.repertoir_emodifreponse_etat import REPERTOIREmodifreponseEtat
from swagger_client.models.repertoir_emodifreponse_etat_etat import REPERTOIREmodifreponseEtatEtat
from swagger_client.models.repertoir_emodifrequest import REPERTOIREmodifrequest
from swagger_client.models.sms_reponse import SMSReponse
from swagger_client.models.sms_reponse_etat import SMSReponseEtat
from swagger_client.models.sms_reponse_etat_etat import SMSReponseEtatEtat
from swagger_client.models.sms_request import SMSRequest
from swagger_client.models.shortlink_request import ShortlinkRequest
from swagger_client.models.shortlink_response import ShortlinkResponse
from swagger_client.models.shortlink_response_etat import ShortlinkResponseEtat
from swagger_client.models.shortlink_response_etat_etat import ShortlinkResponseEtatEtat
from swagger_client.models.sms_unique_request import SmsUniqueRequest
from swagger_client.models.subaccount_add_request import SubaccountAddRequest
from swagger_client.models.subaccount_add_response import SubaccountAddResponse
from swagger_client.models.subaccount_add_response_etat import SubaccountAddResponseEtat
from swagger_client.models.subaccount_add_response_etat_etat import SubaccountAddResponseEtatEtat
from swagger_client.models.subaccount_request import SubaccountRequest
from swagger_client.models.subaccount_response import SubaccountResponse
from swagger_client.models.subaccount_response_etat import SubaccountResponseEtat
from swagger_client.models.subaccount_response_etat_etat import SubaccountResponseEtatEtat
